services:
  nginx:
    image: sandbox_nginx_128
    container_name: nginx
    build: ./nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - docker_sandbox
    volumes:
      - ../:/var/www/project/
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "pet-project.sandbox.local:127.0.0.1"
    links:
      - fpm
    depends_on:
      - fpm

  fpm:
    image: sandbox_php_83
    container_name: fpm
    build: ./php
    volumes:
      - ../:/var/www/project/
    networks:
      - docker_sandbox
    environment:
      - XDEBUG_CONFIG=client_host=host.docker.internal
      - PHP_IDE_CONFIG=serverName=pet-project.sandbox.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=challenge
      - MYSQL_USER=challenge
      - MYSQL_PASSWORD=challenge_pass
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/db/:/docker-entrypoint-initdb.d/
    networks:
      - docker_sandbox

networks:
  docker_sandbox: